---
- hosts: all
  gather_facts: no
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: auto_silent
    devops_server_type: "test"
  #  connection: local
  #  vars_files:
  #    - /home/flamez97/Playbooks/Remote/secret

  tasks:
    - role: drupal
#    - include_vars: ~/Playbooks/restrict
