---
- hosts: all
  gather_facts: no
  become: true

  tasks:
  - name: Import Elasticsearch GPG Key
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

  - name: Get Elasticsearch File
    get_url:
      url: https://class2o2o.s3.amazonaws.com/elastisearch.repo
      dest: /etc/yum.repos.d/elastisearch.repo

  - name: Pause for 1 minute
    pause:
      minutes: 1

  - name: Install Elasticsearch
    yum:
      name: elasticsearch
      state: present
      enablerepo: "elasticsearch"