---
- hosts: all
  gather_facts: no
  become: true

  tasks:
  ##---Installing Elasticsearch---

  - name: Import Elasticsearch GPG Key
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  
  - name: Create Elasticsearch File
    yum_repository:
      name: elasticsearch
      description: Elasticsearch repository for 8.x packages
      baseurl: https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck: yes
      gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled: yes
      state: present

  - name: Pause for 30 seconds
    pause:
      seconds: 30

  - name: Install Elasticsearch
    yum:
      name: elasticsearch
      state: latest
      enablerepo: "elasticsearch"

  ##---Installing Kibana---

  - name: Install Kibana
    yum:
      name: kibana
      state: latest
      enablerepo: "elasticsearch"

  - name: Create Token
    command: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana

  - name: Reload Systemd
    systemd:
      daemon_reload: yes

  - name: Enable Kibana
    systemd:
      name: kibana
      enabled: yes

  - name: Start Kibana
    service:
      name: kibana
      state: started

  ##---Installing Logstash---

  - name: Install Logstash
    yum:
      name: logstash
      state: latest
      enablerepo: "elasticsearch"

  - name: Pause for 15 seconds
    pause:
      seconds: 15

  - name: Start Logstash
    systemd:
      name: logstash
      state: started

  ##--Installing Beats---
  ##Auditbeat
  - name: Install Auditbeat
    yum:
      name: auditbeat
      state: latest

  - name: Enable Auditbeat
    systemd:
      name: auditbeat
      enabled: yes

  ##Filebeat
  - name: Install Filebeat
    yum:
      name: auditbeat
      state: latest

  - name: Enable Filebeat
    systemd:
      name: filebeat
      enabled: yes

  ##Functionbeat
  #- name:

  ##Heartbeat
  - name: Install Heartbeat
    yum:
      name: heartbeat-elastic
      state: latest

  - name: Enable Heartbeat
    systemd:
      name: heartbeat-elastic
      enabled: yes

  ##Metricbeat
  - name: Install Metricbeat
    yum:
      name: metricbeat
      state: latest

  - name: Enable Metricbeat
    systemd:
      name: metricbeat
      enabled: yes

  ##Packetbeat
  - name: Install Packetbeat
    yum:
      name: packetbeat
      state: latest

  - name: Enable Packetbeat
    systemd:
      name: packetbeat
      enabled: yes

  ##Winlogbeat
  #- name:


  ##---Ubuntu---Installing Logstash---

  - name: Get Apt Key
    get_url:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      dest: /temp/GPG-KEY-elasticsearch

  - name: Add Apt Key from file
    apt_key:
      file: /temp/GPG-KEY-elasticsearch
      state: present

  - name: Add Apt Key from URL
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Install Apt Transport
    apt:
      name: apt-transport-https
      state: latest

  - name: Add Apt Repo
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
      state: present

  - name: Update Ubuntu
    apt:
      update_cache: yes

  - name: Install Logstash
    apt:
      name: logstash
      state: latest

  - name: Start Logstash
    systemd:
      name: logstash
      state: started