---
- name: Install Jenkins on CentOS 7
  hosts: all
  become: yes

  tasks:

    - name: Install yum-utils is installed
      yum:
        name: yum-utils
        state: latest

    - name: Add Jenkins repository to yum
      get_url:
        url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Install Java (OpenJDK)
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Ensure Jenkins service is started
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Open firewall ports for Jenkins
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload firewalld
      command: firewall-cmd --reload
      when: firewalld_running.stdout == "running"
      register: firewalld_running
      changed_when: false
      failed_when: false

    - name: Ensure firewalld is running
      shell: firewall-cmd --state
      register: firewalld_running
      changed_when: false
      failed_when: false