---
- hosts: all
  gather_facts: no
#  connection: local
#  vars_files:
#    - /home/flamez97/Playbooks/Remote/secret

#  become: true
  vars:
    devops_server_type: "test"
  tasks:
    - include_role:  name=jenkins-master
#    - include_vars: ~/Playbooks/restrict
