---
- name: Install Jenkins on CentOS 7
  hosts: all
  become: yes

  tasks:
    - name: Add Jenkins repository to yum
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Patch Server
      yum:
        name: "*"
        state: latest

    - name: Install Font
      yum:
        name: fontconfig
        state: latest

    - name: Install Java (OpenJDK)
      yum:
        name: java-11-openjdk
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest

    - name: Start Jenkins and Enable Start Onboot
      service:
        name: jenkins
        state: started
        enabled: yes

#    - name: Wait Before Checking Jenkins Stats
#      wait_for:
#        timeout: 30
#      delegate_to: localhost

    - name: Open Port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        zone: public

    - name: Reload Firewalld
      service:
        name: firewalld
        state: reloaded

#    - name: Display Admin Password
#      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#      register: ps
#
#    - debug: var=ps.stdout_lines

    - name: Display Jenkins Version
      shell: jenkins --version
      register: ps

    - debug: var=ps.stdout_lines

    - name: Display Jenkins Status
      command: systemctl status jenkins
      register: ps

    - debug: var=ps.stdout_lines