---
- name: Installing LAMP
  hosts: all
  become: true

  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache
    service:
      name: httpd
      state: started

  - name: Enable http Port
    firewalld:
      service: http
      permanent: yes
      state: enabled
  
  - name: Confirm http Port Status
    command: sudo firewall-cmd --permanent --list-all
    register: port

  - debug: var=port.stdout_lines

  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: latest
    
  - name: Start MariaDB 
    systemd: 
      state: started
      enabled: yes
  
  - name: Confirm MYSQL status
    command: sudo mysql_secure_installation -y
    register: mysql
  
  - debug: var=mysql.stdout_lines

  - name: Install PHP
    yum: 
      name: php-mysqlnd
      state: latest

  - name: Start PHP
    systemd:
      state: started
      enabled: yes
