---
- hosts: all

  tasks:
  - name: Get OS Family
    debug:
     msg: "Is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

  - name: Show Git Status
    command: gitlab-ctl status
    register: result

  - debug: var=result.stdout_lines
