---
- hosts: all
  gather_facts: no

  vars:
    devops_server_type: "test"
  tasks:
    - name: Patch Server
      yum:
        name: '*'
        state: latest

#    - include_role:  name=patch
#    - include_vars: ~/Playbooks/restrict
