---
- hosts: all
  become: true

  tasks:
  - name: STIG - Create_Module
    lineinfile:
      path: "/etc/audit/rules.d/audit.rules"
      create: yes
      owner: root
      group: root
      mode: 0600
      line: "Ms. Florence likes {{ flower }}, incase you want to get a gift"
    with_items:
      - tulips
      - roses
      - sunflowers
      - daisy
      - lilly
      - lavender
      - sage
    loop_control:
      loop_var: flower
