---
- hosts: all
  become: true

  tasks:
  - name: STIG - Create_Module
    lineinfile:
      path: "/etc/audit/rules.d/audit.rules"
      create: yes
      owner: root
      group: root
      mode: 0600
      line: "-a always,exit -F arch={{ arch }} -S create_module -K module-change"
    with_items:
      - b64
      - b32
    loop_control:
      loop_var: arch
