---
- hosts: all

  tasks:
  - name: Patch Server
    yum:
      name: '*'
      state: latest

  - name: Install wget
    yum:
      name: 'wget'
      state: latest

  - name: Install unzip
    yum:
      name: 'unzip'
      state: latest

  - name: Download Terraform File
    get_url:
      url: https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_linux_amd64.zip
      dest: /tmp/terraform_0.14.4_linux_amd64.zip
      mode: '0777'

  - name: Unzip the Terraform File
    unarchive:
      src: /tmp/terraform_0.14.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: Test Terraform
    shell: terraform -v
    register: ps

  - debug: var=ps.stdout_lines
